---
title: "Assignment 4 - Tables"
author: "Gabrielle Clary"
format: 
  html:
    self-contains: true
editor: visual
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Data Source

### What I want to convey

### Functionality in the table

### Formatting in the table

## Code

```{r}
# load data set and packages 
library(dplyr)
library(mapproj)
library(tidyverse)
library(usdata)
library(ggplot2)
library(DT)

setwd("~/Desktop/STAA566/Assignment4")
ufo <- read.csv("complete.csv", header = T)
# grab only data points for the US
ufo <- ufo[ufo$country == "us",]
# remove data points without a state & duration
ufo <- ufo[!(is.na(ufo$state) | ufo$state ==""),]
ufo <- ufo[!(is.na(ufo$duration..seconds.) | ufo$duration..seconds. ==""),]
# convert state to upper case - for matching on US Map data later
ufo$abbr <- toupper(ufo$state)
# get data summarizations
ufoSummary <- ufo %>%
  group_by(abbr, year)
# get coordinates for the map
tmp_map <- map_data("state")
tmp_map$region <- str_to_title(tmp_map$region)
# create a state abbreviation column since thats what is in our data set
tmp_map$abbr <- usdata::state2abbr(tmp_map$region)
us_state_ufo <- merge(ufoSummary,tmp_map, by = "abbr")
ufo_state <- ufo_state_ufo %>%
  group_by(abbr, year) %>%
  summarise(Total = n(), AvgDurSeconds = mean(duration..seconds.),
            AvgDurMinutes = mean(duration..seconds. / 60))
# double check the lift join worked as expected
us_state_ufo %>% head(n=14)
```

Create and display table

```{r}
DT_table <- us_state_ufo %>%
  select(region, year, Total, AvgDurSeconds, AvgDurMinutes) %>%
  datatable(colnames = c("State", "Year", "Total\nSightings",
                         "Average Sightings\nIn Seconds","Average Sightings\nIn Minutes")) %>%
  formatRound(columns = c(3,4,5), 
              digits = 2)
DT_table
```
